sculpin/sculpin

src/Sculpin/Core/SiteConfiguration/SiteConfigurationFactory.php
The environment is available while pulling in config files so this change
adds the environment to the 'site' variable.
I've tried to avoid code duplication by adding the getConfigFile() method,
but I'm not totally happy with the if .. elseif .. else block.
=> Add 'env' as a default variable available via {{ site.env }} in Twig templates

src/Sculpin/Core/Source/FileSource.php
There exists cases where calling init on an existing source would lose data set from previous calls. The problem is that any time a file is asked to be reprocessed (happens when updated as a part of a collection and other hard to track down cases) the metadata would be read in again from the file. The side effect of this is that ONLY the metadata coming in from the frontmatter would remain. Any metadata set by other extensions or other parts of Sculpin core (things like date tracking and auto layout for proxy source collections) would be lost on init.
This patch works by saving a copy of the data before the new metadata is processed. Afterwards, if data was there originally, it imports it on top of the new metdata w/ clobber set to `false`. This will ensure that data that is already set …
=> Import original data for a source when init is called again

src/Sculpin/Contrib/Taxonomy/ProxySourceTaxonomyIndexGenerator.php
This replaces #192. I think this is a simpler approach and results in less code needing to be written.
Usage would be either:
```twig
{% if page.tags %}
<p class="tags">Tagged with
{% for tag in page.tags %}
<a class="tag" href="{{ site.url }}/{{ page.tag_html_index_permalinks[tag] }}">{{ tag }}</a>{% if not loop.last %}, {% endif %}
{% endfor %}
</p>
{% endif %}
```
... or
```twig
{% if page.tags %}
<p class="tags">Tagged with
{% for tag,permalink in page.tag_html_index_permalinks %}
<a class="tag" href="{{ site.url }}/{{ permalink }}">{{ tag }}</a>{% if not loop.last %}, {% endif %}
{% endfor %}
</p>
{% endif %}
```
Either would work.
The nice things over #192 are that 1) it only creates these for taxonomies for which an index page even exists and 2) it accounts for the fact that you …
=> Inject a {taxon}_{type}_index_permalinks for every type of taxonomy index created

src/Sculpin/Core/Formatter/FormatterManager.php, src/Sculpin/Core/Permalink/SourcePermalinkFactory.php
From @asm89; references balrog support for `$relativeUrl`. Idea being that you don't want to have the full site URL in every link.
Refs #47
=> Experimental support for `root_relative_url`

composer.lock
Replaces #205 as it only updates the minimum set of dependencies to get us a new version of composer@dev instead of composer@alpha. Sometimes solver still confuses me. :-/ Not sure why we had to update these deps as well; nothing I could see in the dependencies should have required this.
@dragonmantank if you can try out your site w/ this build that would be helpful to me. See if it fixes your problem. We should merge this and update the phar soon.
=> Updated dependencies to a ore modern composer, json-schema, and symfony finder, process, and console.

composer.json, composer.lock, src/Sculpin/Bundle/MarkdownBundle/MarkdownConverter.php, src/Sculpin/Bundle/MarkdownBundle/composer.json
This enables the use of automatically generating deep links to h[1-6] headers.
Hope you are happy with the approach, otherwise, let me know!
The effect is that markdown such as this:
```md
```
Will now be transformed to:
```html
<h3 id="my-first-webpage">My first webpage</h3>
```
=> Updated to php-markdown 1.5.0

src/Sculpin/Bundle/MarkdownBundle/DependencyInjection/Configuration.php
mkdn is an acceptable extension as per
https://github.com/github/markup/tree/master#markups
=> Add mkdn extension to markdown extension list

src/Sculpin/Core/Permalink/SourcePermalinkFactory.php
A simple - maybe too simple - solution to the problem in https://github.com/sculpin/sculpin/issues/172
=> Make sure that all twig files end up as .html files.

src/Sculpin/Core/Tests/Permalink/SourcePermalinkFactoryTest.php
This will hopefully help ensure that we will not see regressions on some of the more finicky bits of the permalink stuff. Still needs a lot of work but it is a start.
=> Add tests for source permalink factory.

src/Sculpin/Bundle/MarkdownBundle/MarkdownConverter.php
Fixes Issue #222
This change goes a bit further than the last PR. It now does a better
job stripping markup from headers to generate more accurate values for
the id="" attribute.
This is a table of headers that I've tested, and their new output:
Output for the preceeding headers:
<h2 id="header1">Header1</h2>
<h2 id="header2--">Header2 [ ]</h2>
<h2 id="header3"><a href="http://sculpin.io/">Header3</a></h2>
<h2 id="header4"><small>header4</small></h2>
<h2 id="sculpin"><a href="http://sculpin.io/">Sculpin</a></h2>
=> Fix generating id="" headers for headers that have markup.

src/Sculpin/Contrib/ProxySourceCollection/ProxySourceItem.php
`$proxy->offsetSet('foo', 'bar')` or `$proxy['foo'] = 'bar'` should call `$proxy->setFoo('bar')` if method `setFoo()` exists in the `ProxySourceItem`.
I am not sure if the magic `set*` implementation in `offsetSet` is desired after all.
1. This issue exists since Jan 5 2014 introduced here: https://github.com/sculpin/sculpin/commit/b5009c51512623456d782bcebbdb3d2f23270406#diff-93bd9bcccd85a4cb1252ac59d0f9c947R114
2. `offsetGet` does not not check for `get*` methods
=> Fix ArrayAccess setter for "set"-Prefixed methods in ProxySourceItem

src/Sculpin/Bundle/PaginationBundle/PaginationGenerator.php
`PaginationGenerator::generate()` typehints a `SourceInterface` so the `duplicate()` method has no `$options` argument. `$options` was an empty array anyway.
=> Fix call to SourceInterface::duplicate() with too many arguments

src/Sculpin/Core/Source/ProxySource.php, src/Sculpin/Core/Tests/Source/ProxySourceTest.php
`ProxySource::setFormattedContent()` did not call the correct method on the decorated object.
=> Fix ProxySource::setFormattedContent()

src/Sculpin/Core/Permalink/SourcePermalinkFactory.php, src/Sculpin/Core/Tests/Permalink/SourcePermalinkFactoryTest.php
I found where the trailing slash behavior was introduced and it has been fixed. We should not force trailing backslash if the user does not request it.
=> Revert forced trailing slash behavior.

src/Sculpin/Bundle/MarkdownBundle/MarkdownConverter.php, src/Sculpin/Contrib/Taxonomy/ProxySourceTaxonomyIndexGenerator.php
- Short array syntax was introduced in PHP 5.4 and is not backwards
compatible.
=> Issue #239: Replace short array syntax for PHP 5.3 compatibility

.gitignore, Bootstrap.php, composer.json, composer.lock, phpunit.xml.dist, src/Sculpin/Tests/Functional/Fixture/source/hello_world.md, src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/GenerateFromMarkdownTest.php
I put together some basic end-to-end functional tests against the sculpin binary. Each test creates a temporary `SculpinTestProject` directory, to which you can add whatever source files / layouts / config your want, run the sculpin binary, then make sure the generated output is as expected.
These tests use a base `FunctionalTestCase` class, which provides a number of utilities for writing functional tests as I have described.
My motivation for this is:
- I noticed that there is test coverage missing for several of the bundles
- As a contributor, it's much less scary for me to propose changes if I know I'm not breaking existing behavior
- As a contributor, there is a lower barrier to entry to me to write functional tests than unit tests.
Specifically, I'm planning to do some work on the …
=> Functional test case

src/Sculpin/Core/Source/FilesystemDataSource.php
This change will include dotfiles (such as .htaccess) in the generated output, resolving issue #121. It continues to ignore VCS-related files (such as .git).
=> Include dot files in output generation

src/Sculpin/Bundle/SculpinBundle/Command/GenerateCommand.php
I thought it would be good if there was an option to clear the output directory out first prior to generation.
=> Adds a clean option to the generate command.

composer.json, composer.lock
We are now tracking Composer in a better way ( ^1.0 instead of the oldschool 1.0.*@dev ) so we should continue to stay up to date. We now also track dflydev/embedded-composer directly instead of the subtree splits as those are somewhat dead and I'm not sure I'm going to bother resurrecting them.
Effective immediately I'm going to be dropping support for both Embedded Composer and phar distribution for Sculpin. There are 2.0.*
If the people chiming in on #297 could check to see if this will fix their issues (minus the fact that there will be no phar release) it would be a huge help. If there is more work that needs to be done at the dependency layer let me know.
My main goal for 2.1 at this point is to get it running on PHP 7 from a source install.
I will likely do a much longer blog post …
=> Update things to hopefully work better with PHP 7.

src/Sculpin/Core/Permalink/SourcePermalinkFactory.php, src/Sculpin/Core/Tests/Permalink/SourcePermalinkFactoryTest.php
fixes #275 
Not a big fan of the str_replace based on the '/' string constant, but using DIRECTORY_SEPARATOR makes testing this behavior impossible outside of windows platform.
=> Sanitizing url path for Windows platform in SourcePermalinkFactory

src/Sculpin/Bundle/SculpinBundle/Console/Application.php, src/Sculpin/Bundle/StandaloneBundle/Command/CacheClearCommand.php
Probably everything here is self-explanatory. Nonetheless:
- Check the [BundleInterface API docs](http://api.symfony.com/2.3/Symfony/Component/HttpKernel/Bundle/BundleInterface.html)
- The base [Kernel class boot method](https://github.com/symfony/HttpKernel/blob/2.3/Kernel.php#L116) largely accomplishes the same work as the override, which ends up compiling the container twice (see `Kernel::initializeContainer()`). (2016 August 12: Well, apparently not. The override is what allowed tests to pass. I've removed that commit.)
=> A small amount of cleanup.

.travis.yml, composer.json, composer.lock, phpcs.xml, phpunit.xml.dist
- Travis is updated to run tests with lowest/composer.lock/latest dependencies
- PHP_Codesniffer added with PSR-2 ruleset
- Phpunit bumped to 4.8.x, the last one supporting PHP 5.4
Includes/depends on #328
=> Improve travis setup, upgrade phpunit and add php_codesniffer

src/Sculpin/Bundle/SculpinBundle/DependencyInjection/SculpinExtension.php
Configuration keys are duplicated between the extension and the config class. This simplifies it and removes that duplication.
=> Removed config duplication

.gitignore, .travis.yml, composer.json, composer.lock, phpcs.xml
- Code coverage is generated with php-dbg
- QA tools with call parameters are added to `composer.json` as scripts:
- `cs-check`
- `cs-fix`
- `test`
- `test-coverage`
- `phpstan`
- Phpstan will run on build along with cs checks but is forced to not fail at the moment. It might become mandatory check once currently reported issues are fixed and level of possible false positives is evaluated.
=> [WIP] Add static code analyzer phpstan and improve QA tools setup

CHANGELOG.md, src/Sculpin/Core/Permalink/SourcePermalinkFactory.php, src/Sculpin/Core/Tests/Permalink/SourcePermalinkFactoryTest.php
This fix limits scope of #233 to permalinks that have no extension or end in '.md' or '.twig'
=> Fix regression introduced by #233

CHANGELOG.md, src/Sculpin/Core/Permalink/SourcePermalinkFactory.php, src/Sculpin/Core/Tests/Permalink/SourcePermalinkFactoryTest.php
i want to define slugs with paths in them. i see no reason why this should not be allowed, as e.g. pretty uses the path to the file which also contains folders. in my project it works fine with this change.
=> allow slug to specify directory separators

.travis.yml
HHVM build fails only because Precise is not supported anymore.
=> Change Travis distro to Trusty

src/Sculpin/Bundle/TwigBundle/Environment.php, src/Sculpin/Bundle/TwigBundle/Resources/config/services.xml, src/Sculpin/Bundle/TwigBundle/TemplateResetter.php, src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/GenerateFromMarkdownTest.php
This is a bit hacky, but it should fix issue #362 and hopefully get the `develop` branch on track to merge into master.
=> Use reflection to bring back Twig template cache invalidation

composer.json, composer.lock
I would like to merge `develop` (aka Sculpin `3.0.x-dev`) into `master`, which is currently targeted as `2.1.x-dev`. I think the best way to do that, while preserving existing installs at `2.1.x-dev`, is to modify the `composer.json` in this way.
Please correct me if I'm wrong. I'm quite unfamiliar with the `branch-alias` feature.
=> Change dev-master to 3.0.x-dev, add dev-2.x

src/Sculpin/Bundle/ContentTypesBundle/Command/ContentCreateCommand.php
This command will output the required YAML for adding a custom content type, and (optionally) output boilerplate files for the new content type. It also supports custom taxonomies.
=> Command to help users create new custom content types

src/Sculpin/Bundle/PaginationBundle/PaginationGenerator.php, src/Sculpin/Bundle/PaginationBundle/Resources/config/services.xml
The `PaginationGenerator` needs to use proper permalinks rather than
trying to figure them out in its own. So use the `SourcePermalinkFactory`.
=> Use permalink factory when paginating

src/Sculpin/Core/Source/AbstractSource.php
Hi!
I use this bundle https://github.com/rjkip/SculpinRstBundle to generate the RST format, but the generated files are rst extension, not html (as expected), but to achieve this, we need to set the `canBeFormatted` property to true, which the given PR does.
A big request to view and accept this PR. Thank you!
cc @beryllium
=> Add setter for canBeFormatted property of AbstractSource class

src/Sculpin/Bundle/TwigBundle/FlexibleExtensionFilesystemLoader.php
Because if there is no extension on the latest iteration is exception occurs, which currently is not catched, and the work will be completed a fatal error.
https://github.com/sculpin/sculpin/blob/70acab357b1f4ff8bdff5b6a3339d30183cd83ca/src/Sculpin/Bundle/TwigBundle/FlexibleExtensionFilesystemLoader.php#L105
=> Fix uncaught exception on checking the existence of a loader

src/Sculpin/Bundle/ThemeBundle/ThemeRegistry.php
Since strict typing is used, currently there is such an error:
`Fatal error: Uncaught TypeError: dirname() expects parameter 1 to be string, object given on line 48`
=> Fix type error

src/Sculpin/Bundle/SculpinBundle/Console/Application.php, src/Sculpin/Bundle/SculpinBundle/SculpinBundle.php
In current moment we can see such errors:
```
PHP Deprecated: Auto-registration of the command 
"Sculpin\Bundle\SculpinBundle\Command\ServeCommand" is 
deprecated since Symfony 3.4 and won't be supported in 4.0. 
Use PSR-4 based service discovery instead
```
This is due to the fact that the commands must be explicitly registered as services, this PR adds support for this.
The source of the implementation was taken from the framework-bundle https://github.com/symfony/framework-bundle/blob/505aa68e04b160318c68b61f02fc1c341f43fa34/Console/Application.php
=> Add support for commands as services

composer.json, composer.lock, src/Sculpin/Bundle/ContentTypesBundle/DependencyInjection/SculpinContentTypesExtension.php, src/Sculpin/Bundle/MarkdownBundle/Resources/config/services.xml, src/Sculpin/Bundle/MarkdownTwigCompatBundle/Resources/config/services.xml, src/Sculpin/Bundle/SculpinBundle/Resources/config/services.xml, src/Sculpin/Bundle/StandaloneBundle/Resources/config/services.xml, src/Sculpin/Bundle/TextileBundle/Resources/config/services.xml, src/Sculpin/Bundle/ThemeBundle/Resources/config/services.xml, src/Sculpin/Bundle/TwigBundle/Resources/config/services.xml
There are a number of deprecation notices that were brought to my attention by @lex111. I've fixed a few of them here by setting services Public, but there are stickier situations in the codebase that will need to be resolved, like these:
> **PHP Deprecated: Passing a boolean flag to toggle exception handling is deprecated since version 3.1 and will be removed in 4.0. Use the PARSE_EXCEPTION_ON_INVALID_TYPE flag instead.**
This is caused by one of the Sculpin dependencies. It tries to call `->parse($data, true)` on the Yaml component, which is not cool. I have [submitted a PR](https://github.com/dflydev/dflydev-dot-access-configuration/pull/9) to the dependency to try and get it fixed.
> **PHP Deprecated: The Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher class is …
=> Fix deprecation notices relating to Symfony 4.0 changes

src/Sculpin/Bundle/StandaloneBundle/Resources/config/services.xml
It is very important! 
Forgive me, I broke backward compatibility in [my PR](https://github.com/sculpin/sculpin/pull/383): built-in Sculpin events is worked, but custom ones ([example](https://github.com/shopware/devdocs/blob/93cb1789f9b93acf88d82d545ae0883d21e892eb/app/src/AnchorListener.php#L19)) **will not work** because [this condition in event_dispatcher will be true](https://github.com/symfony/event-dispatcher/blob/d8eb135cc2886e01e829f4fd6be148342de39454/DependencyInjection/RegisterListenersPass.php#L51).
Please accept this change as soon as possible!
cc @beryllium @simensen
=> Make a public service Event Dispatcher

composer.json
Because Sculpin [uses](https://github.com/sculpin/sculpin/blob/180253cc6a15ba070261e4bb7694f844385b3768/src/Sculpin/Core/Permalink/SourcePermalinkFactory.php#L207) the `iconv` function, we need to add it to the Composer.
cc @beryllium @simensen
=> Add ext-iconv to composer.json

phpcs.xml
=> Add Generic.Arrays.DisallowLongArraySyntax rule

.gitignore, phpcs.xml, src/Sculpin/Bundle/SculpinBundle/Command/InitCommand.php, src/Sculpin/Bundle/SculpinBundle/Resources/config/services.xml, src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/InitCommandTest.php
This new command (`sculpin init`) will prep a very bare-bones set of files in order to get people up and running faster.
The files it creates are:
```
app/SculpinKernel.php
app/config/sculpin_kernel.php
app/config/sculpin_site.php
source/index.md
source/_views/default.html
```
It will ensure the `app` and `source` directories do not exist before it tries to create them.
There is a lot of room for improvement, from adding parameters to pre-fill information all the way up to creating an interactive menu for choosing whether the site should be a Company site, a Blog, or a Portfolio. That will hopefully be possible in the future.
=> Create basic initialization command for clean-slate projects.

src/Sculpin/Bundle/SculpinBundle/Command/GenerateCommand.php, src/Sculpin/Bundle/SculpinBundle/DependencyInjection/Compiler/DirectoryOverridePass.php, src/Sculpin/Bundle/SculpinBundle/HttpKernel/AbstractKernel.php, src/Sculpin/Bundle/SculpinBundle/HttpKernel/KernelFactory.php, src/Sculpin/Bundle/SculpinBundle/SculpinBundle.php, src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/GenerateCommandTest.php
One of the goals for Sculpin 3.0 is to have not just an `--output-dir` option, but also a `--source-dir` option. This PR attempts to deliver on that, and it also attempts to fix a potential issue with `--output-dir` as it relates to sculpin extensions like *icelus* (which in my testing was continuing to write to `output_dev/` - not desirable).
This adds a `DirectoryOverridePass` compiler pass to update the existing container parameters with the newly-overridden values.
=> Add an option to specify a different `source` directory.

.travis.yml
Travis now has experimental support for testing under OS X (and Windows, but that doesn't seem to play nicely with PHP yet). Maybe it will help Sculpin to try and test under these common user envs.
Technically their Windows support doesn't include PHP, and their OS X support may not support it either. Let's find out. (Update: discovered that yes, OS X can be done, but Windows is still difficult.)
=> Add travis support for OS X tests and PHP 7.3

src/Sculpin/Core/Permalink/SourcePermalinkFactory.php, src/Sculpin/Core/Tests/Permalink/SourcePermalinkFactoryTest.php
Allows for permalinks to include the folders. Example would be a file in _posts/something/other.md could then have a permalink setting of /posts/:folder:basename.html and result in /posts/something/other.html as output, while _posts/a-post.md would still output /posts/a-post.html as well.
Will create a PR for the docs as well.
=> Add :folder permalink property

src/Sculpin/Bundle/TextileBundle/TextileConverter.php
the `textileThis` method has been renamed to `parse` and textileThis is deprecated.
=> adjust for textile 3.6

src/Sculpin/Core/DataProvider/DataProviderManager.php, src/Sculpin/Core/Generator/GeneratorManager.php
In the case of the DataProviderManager, an invalid value triggers a noisy stack trace (`E_ALL`) on the console, whereas the exception from this change is handled by the console application.
For the GeneratorManager this change points me directly to the offending file.
=> Generator exceptions

src/Sculpin/Bundle/SculpinBundle/Resources/config/services.xml
In a standard Symfony environment `%kernel.root_dir%` will be `src/`, whereas `%kernel.project_dir%` is minus that subdirectory's use. 
Under Sculpin's normal use-case this shouldn't change anything.
=> Swap %kernel.root_dir% for %kernel.project_dir%

src/Sculpin/Bundle/SculpinBundle/Command/GenerateCommand.php, src/Sculpin/Bundle/TwigBundle/TwigFormatter.php, src/Sculpin/Core/Io/ConsoleIo.php, src/Sculpin/Core/Output/FilesystemWriter.php, src/Sculpin/Core/Sculpin.php, src/Sculpin/Core/Source/SourceSet.php, src/Sculpin/Tests/Functional/FunctionalTestCase.php
_Please close if this is not in-line with project design_ :+1: 	
This PR moves the bulk of exception handling to the console command:
- When running the server prints `<error>Error message details</>`
- When running in debug (`-vvv`) prints `<comment>Stack trace array</>`
- Running in watch mode (no server) prints;
- `<error>Error message details</>`
- `<comment>Stack trace array</>`
- Otherwise the exception is re-thrown
Makes life a lot easier to fix problems, including the hidden in the `FunctionalTestCase` :wink:
=> Enhance exception handling

src/Sculpin/Bundle/ThemeBundle/ThemeRegistry.php
Hit this when emptying the `theme.yml` file.
=> Cast Yaml::parse() result to array as it can return null

src/Sculpin/Bundle/ThemeBundle/ThemeTwigExtension.php, src/Sculpin/Bundle/ThemeBundle/ThemeTwigLoader.php, src/Sculpin/Bundle/TwigBundle/Environment.php, src/Sculpin/Bundle/TwigBundle/FilesystemLoader.php, src/Sculpin/Bundle/TwigBundle/FlexibleExtensionFilesystemLoader.php, src/Sculpin/Bundle/TwigBundle/Resources/config/services.xml, src/Sculpin/Bundle/TwigBundle/TwigFormatter.php
This PR moves Twig class/import use to namespaces, cleaning up deprecation warnings in the process.
A note on removing ExistsLoaderInterface: https://twig.symfony.com/doc/2.x/deprecated.html#interfaces
If #421 is accepted prior to this, the PHPDoc in `GenerateCommand` will need tweaking too :smiley_cat:
=> Move Twig classes/imports to namespaces

src/Sculpin/Bundle/ContentTypesBundle/DependencyInjection/SculpinContentTypesExtension.php, src/Sculpin/Contrib/Taxonomy/PermalinkStrategyCollectionFactory.php
When working on a (pure) Symfony 4.2 project the container dumping will fail as `Sculpin\Contrib\Taxonomy\PermalinkStrategyCollection` is built as an object in the bundle's DI extension, instead of by the container, resulting in the exception:
```
[Symfony\Component\DependencyInjection\Exception\RuntimeException]             
Unable to dump a service container if a parameter is an object or a resource.  
```
This PR moves construction to a service factory, and the service to a `Symfony\Component\DependencyInjection\Definition`.
=> Migrate PermalinkStrategyCollection definition to the container

src/Sculpin/Core/Sculpin.php
In my sculpin project, I have a button in the top of every generated markdown file which redirects me to the edit page of that file on gitlab. In this case i would always need the current file path to land on the current file on gitlab and this is why i added the relative pathname and file name for the current opened file.
=> Add relative_pathname and filename for current file

composer.json, composer.lock, src/Sculpin/Contrib/ProxySourceCollection/ProxySourceCollection.php
Sculpin can sometimes get caught in infinite loops when in `generate --watch` mode. This seems partly related to undefined behaviour of `uasort()` when dealing with arrays of certain sizes containing comparison keys that are equal.
Add a "StableSort" library and consume it inside `ProxySourceCollection::sort()`.
Maybe the full library isn't needed? The logic of that specific uasort implementation could be inlined to avoid pulling in the dependency. Not sure the ideal approach to use.
This doesn't fully solve the problems presented in #308, it just addresses one specific circumstance that came up during exploration of the problem.
It looks like the remainder of the issue is related to what effectively acts like nested sequences - sorting subtypes within supertypes, in a way. The main …
=> Stabilize MetaSorter sorting

src/Sculpin/Contrib/ProxySourceCollection/ProxySourceCollectionDataProvider.php, src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/GenerateFromMarkdownTest.php
A correction to the way files are processed by Sculpin generators. Includes tests. This issue was reported in Issue #432.
If a file is encountered that matches the filter patterns (e.g., `_posts/**`) but cannot be formatted, it will be marked as `ShouldBeSkipped`. If it is hidden, this will be done silently - otherwise, a `Skipping empty or unknown file: ` message will be displayed.
Overall this is intended as a patch-level improvement. However, it could introduce some unexpected breakages because of how it prevents files from being erroneously written straight to disk (e.g., `sculpin/output_dev/_posts/blog-post-file-with-no-extension` will no longer be written if `sculpin/source/_posts/blog-post-file-with-no-extension` exists; previously, this would completely bypass the permalink …
=> Skip certain ContentType files

composer.json, composer.lock
Looks like the composer update bumps a bunch of symfony dependencies from 4.2.x to 4.4.x (and 5.x in one case) - not sure if that's going to fly. We'll see what Travis says, I guess.
=> Update michelf/php-markdown to 1.9 and run composer update

composer.json, composer.lock, src/Sculpin/Bundle/SculpinBundle/HttpServer/HttpServer.php
This minimal changeset updates react/http to the stable `v1.0.0` released a few days ago: https://github.com/reactphp/http/releases/tag/v1.0.0
I've updated the code to resolve some minor BC breaks, but this doesn't seem to be covered by the existing test suite afaict. I've manually checked the `sculpin serve` command and verified this appears to work as expected.
Let me know if there's anything else that needs to be done to get this merged :+1:
=> Update react/http to v1.0.0

src/Sculpin/Bundle/TwigBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/TwigBundle/DependencyInjection/SculpinTwigExtension.php, src/Sculpin/Bundle/TwigBundle/Resources/config/services.xml, src/Sculpin/Bundle/TwigBundle/WebpackEncoreHelper.php, src/Sculpin/Tests/Functional/Fixture/webpack_manifest/manifest.json, src/Sculpin/Tests/Functional/Fixture/webpack_manifest/manifest_test.md, src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/GenerateCommandTest.php
This helper exposes the `manifest.json` generated by webpack as a global variable in Twig, so that `production` assets can be referenced with their file hashes.
To configure the helper, define this parameter in your `app/config/sculpin_kernel.yml` or `app/config/sculpin_kernel_prod.yml` file:
```yaml
sculpin_twig:
webpack_manifest: build/manifest.json
```
The above example tells Sculpin to look in the `project_dir/source/` folder for `build/manifest.json`.
Once this is pointing at the correct file, you can use these Twig snippets to include your CSS and JS files:
```twig
<link rel="stylesheet" href="{{ site.url }}{{ webpack_manifest['build/css/app.css']|default('/build/css/app.css') }}"/>
<script type="text/javascript" src="{{ site.url }}{{ …
```
=> Add a webpack encore helper to Twig

.github/workflows/codesniffer.yml, .github/workflows/phpstan.yml, .github/workflows/phpunit.yml
Adds actions for phpunit, phpstan, and codesniffer.
Does not fully implement the matrices and OS X/Windows support of the TravisCI configuration, that will come later.
=> Add some GitHub actions

src/Sculpin/Bundle/ContentTypesBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/MarkdownBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/PaginationBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/PostsBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/SculpinBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/TextileBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/ThemeBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/TwigBundle/DependencyInjection/Configuration.php
This PR attempts to fix deprecated `root` method in TreeBuilder.
Since Symfony 4.3, it is deprecated to use `root` method in TreeBuilder to set the rootNode.
Referencing: [New in Symfony 4\.2: Important deprecations \(Symfony Blog\)](https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes)
=> Fix deprecated method in TreeBuilder

bin/sculpin
Composer on WSL/Windows creates proxies in vendor/bin. This leads to
weird include behaviour, so by making the path to bin/sculpin.php
absolute, we force the include of the right file.
=> Make path to bin/sculpin.php absolute

composer.json, composer.lock, src/Sculpin/Bundle/TwigBundle/Resources/config/services.xml
As reported in #465, this package is deprecated with no replacement suggested. In the default Sculpin configuration, only the IntlExtension is used.
However, it is entirely possible that downstream consumers of Sculpin may be using these filters or some of the other Twig\Extensions classes. This is technically a bit of a BC break, as a result. The users would have to manually intervene, to locally include twig\extensions and configure them by hand in their local Sculpin configuration.
=> Remove dependency on twig/extensions

.gitignore
I added `.phpunit.result.cache` and `.php-version` to gitignore.
`.php-version` is a file that is required when using `phpenv`.
=> add .php-version and .phpunit.result.cache to gitignore

src/Sculpin/Contrib/ProxySourceCollection/ProxySourceCollection.php, src/Sculpin/Contrib/ProxySourceCollection/ProxySourceItem.php, src/Sculpin/Core/Permalink/SourcePermalinkFactory.php
- ArrayAccess interface has change to implement `mixed` types
on the methods. This may create a BC break with people using
Sculpin on PHP 7.x, which the project is not yet prepared to do.
Therefore, it is preferable to use the attributes for now.
=> Add PHP attributes to suppress some PHP 8.1 deprecation notices

src/Sculpin/Core/Permalink/SourcePermalinkFactory.php
Alpine Linux (and possibly other environments?) don't support the use of `//TRANSLIT` and `//IGNORE` in `iconv()` calls. When those modifiers are used in an unsupported environment, `iconv()` emits a warning and returns `FALSE`.
Reference: https://github.com/docker-library/php/issues/240#issuecomment-250213168
During permalink generation in Sculpin, that behavior causes `FALSE` to be passed to the subsequent call to `preg_replace()` — which throws a fatal error in PHP 8 when strict type-checking is enabled.
This patch ensures that if `iconv()`conversion fails, the original `$param` value is used instead.
=> Fix permalink generation on PHP 8 when //TRANSLIT isn't supported

composer.json, composer.lock, src/Sculpin/Bundle/MarkdownBundle/PhpMarkdownExtraParser.php
A few deprecation notices spoil the broth; they make output-sensitive tests fail, and clutter up CI tooling and CLI output.
The main culprit was in the AbstractConfiguration class, but updating composer dependencies fixed that by pulling in a well-placed `(string)`.
The next most notable culprint was hiding in MarkdownExtra, but Sculpin already overrides this as `PhpMarkdownExtraParser` so it was trivial to add a method override and perform the `(string)` manually.
=> Fix PHP 8 deprecation notices

composer.json, src/Sculpin/Bundle/SculpinBundle/Resources/config/services.xml, src/Sculpin/Core/Source/FileSource.php, src/Sculpin/Core/Source/FilesystemDataSource.php, src/Sculpin/Core/Tests/Source/FileSourceTest.php
[Dflydev\Canal](https://github.com/dflydev/dflydev-canal/) is not fully compatible with PHP 8.2, which makes Sculpin also not compatible.
So first I upgraded Canal https://github.com/dflydev/dflydev-canal/pull/1, but @dflydev suggested that the package is not maintained and might be good to replace it or find a maintainer.
[thephpleague/mime-type-detection](https://github.com/thephpleague/mime-type-detection) package is simpler, but has the same purpose and seems to be good enough for Sculpin, and most importantly, actively maintained.
This, however, bumps the minimal PHP version to 7.4. But since 7 has reached end-of-life anyway, it makes sense to just leave 8.0.
=> Replace mime type detection package for PHP 8.2 compatibility

src/Sculpin/Bundle/ContentTypesBundle/Command/ContentCreateCommand.php, src/Sculpin/Bundle/SculpinBundle/Command/ContainerDebugCommand.php, src/Sculpin/Bundle/SculpinBundle/Command/GenerateCommand.php, src/Sculpin/Bundle/SculpinBundle/Command/InitCommand.php, src/Sculpin/Bundle/SculpinBundle/Command/ServeCommand.php, src/Sculpin/Bundle/StandaloneBundle/Command/CacheClearCommand.php, src/Sculpin/Bundle/ThemeBundle/Command/ListCommand.php, src/Sculpin/Tests/Functional/GenerateFromMarkdownTest.php
Since PHP7.3, we've been able to use heredoc indentation to clean up these sorts of inline references.
- HEREDOCs are reindented so as not to be at col(0) position
- HEREDOC label is standardized to `EOT` (End Of Text)
=> Update heredoc indents

src/Sculpin/Bundle/SculpinBundle/HttpKernel/AbstractKernel.php, src/Sculpin/Core/SiteConfiguration/SiteConfigurationFactory.php, src/Sculpin/Tests/Functional/Fixture/config/sculpin_site.yml, src/Sculpin/Tests/Functional/Fixture/source/hello_world.md, src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/GenerateCommandTest.php
@beryllium in `alpha2` I've encountered that the config is not loading properly
(e.g. `$this->configuration->get('title')` or `{{ site.title }}` was missing),
this should help.
Added a test to proof it.
=> Fix `projectDir`

src/Sculpin/Bundle/SculpinBundle/Console/Application.php, src/Sculpin/Contrib/ProxySourceCollection/ProxySourceCollection.php, src/Sculpin/Contrib/ProxySourceCollection/ProxySourceCollectionDataProvider.php, src/Sculpin/Contrib/ProxySourceCollection/ProxySourceItem.php, src/Sculpin/Core/Console/Command/ContainerAwareCommand.php, src/Sculpin/Core/Formatter/FormatterManager.php, src/Sculpin/Core/Generator/GeneratorManager.php, src/Sculpin/Core/Sculpin.php, src/Sculpin/Core/Source/ConfigFilesystemDataSource.php, src/Sculpin/Core/Source/FilesystemDataSource.php, src/Sculpin/Core/Source/Filter/AntPathFilter.php
Fixes implicit nullable parameter deprecation messages on PHP 8.4.
- [RFC](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types)
- [PHP 8.4: Implicitly nullable parameter declarations deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)
Nullable parameters are a PHP 7.1 feature, but our minimum PHP version requirement is PHP 7.1, so this is a safe change.
=> [PHP 8.4] Updates to avoid implicit nulable parameter deprecation
