src/Sculpin/Bundle/MarkdownBundle/MarkdownConverter.php
So the IDE stops shouting at me.
=> Fix typo in DocBlock

src/Sculpin/Core/Permalink/SourcePermalinkFactory.php, src/Sculpin/Core/Permalink/SourcePermalinkFactoryInterface.php, src/Sculpin/Core/Sculpin.php
`SourcePermalinkFactory` is already a nice stateless service but lacks an interface so it can be replaced or decorated.
=> Introduce interface for SourcePermalinkFactory

README.md
Pie Crust is no more in PHP. The new version is in Python
=> Update PieCrust details in README

src/Sculpin/Bundle/SculpinBundle/HttpServer/HttpServer.php
Looking for review & merge by @sculpin/management.
=> Return some content w/ the 404 response. Closes #105.

composer.lock
We let #212 slip through without updating the `composer.lock`. This fixes that.
Looking for another @sculpin/management to review & merge this one.
=> Updated lock file (re: #212)

src/Sculpin/Core/Converter/ConverterManager.php, src/Sculpin/Core/Formatter/FormatterManager.php, src/Sculpin/Core/Generator/GeneratorManager.php, src/Sculpin/Core/Sculpin.php
I can't use Sculpin bundles with Symfony if the actual EventDispatcher is required, so this pull request uses interfaces instead.
=> use EventDispatcherInterface instead of concrete implementation.

composer.json, composer.lock
Follow-up to https://github.com/sculpin/sculpin/pull/264
=> Updating composer.lock.

src/Sculpin/Bundle/PaginationBundle/PaginationGenerator.php, src/Sculpin/Core/Permalink/SourcePermalinkFactory.php
=> Fix pagination for tags and categories

.scrutinizer.yml, .travis.yml
And enable coverage upload from travis
=> Add initial scrutinizer config

.travis.yml, CHANGELOG.md, composer.json
=> Drop php 5 support in v3

.travis.yml, src/Sculpin/Bundle/ContentTypesBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/ContentTypesBundle/DependencyInjection/SculpinContentTypesExtension.php, src/Sculpin/Bundle/MarkdownBundle/DependencyInjection/Configuration.php, src/Sculpin/Bundle/MarkdownTwigCompatBundle/ConvertListener.php, src/Sculpin/Bundle/PostsBundle/DependencyInjection/SculpinPostsExtension.php, src/Sculpin/Bundle/SculpinBundle/Command/ContainerDebugCommand.php, src/Sculpin/Bundle/SculpinBundle/Command/GenerateCommand.php, src/Sculpin/Bundle/SculpinBundle/Command/SelfUpdateCommand.php, src/Sculpin/Bundle/SculpinBundle/Console/Application.php, src/Sculpin/Bundle/SculpinBundle/DependencyInjection/Compiler/PathConfiguratorPass.php, src/Sculpin/Bundle/SculpinBundle/HttpKernel/KernelFactory.php, src/Sculpin/Bundle/SculpinBundle/HttpServer/HttpServer.php, src/Sculpin/Bundle/StandaloneBundle/DependencyInjection/Compiler/RegisterKernelListenersPass.php, src/Sculpin/Bundle/ThemeBundle/ThemeRegistry.php, src/Sculpin/Contrib/ProxySourceCollection/Sorter/MetaSorter.php, src/Sculpin/Core/Permalink/SourcePermalinkFactory.php, src/Sculpin/Core/Source/FileSource.php, src/Sculpin/Core/Source/FilesystemDataSource.php, src/Sculpin/Core/Source/Map/CalculatedDateFromFilenameMap.php, src/Sculpin/Core/Tests/Formatter/FormatContextTest.php, src/Sculpin/Core/Tests/Source/FileSourceTest.php, src/Sculpin/Core/Tests/Source/Map/CalculatedDateFromFilenameMapTest.php, src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/GenerateFromMarkdownTest.php
PSR-2 rules will be enforced by travis with this PR
=> Apply coding style rules and enable travis cs check

composer.json, composer.lock, src/Sculpin/Bundle/SculpinBundle/HttpServer/HttpServer.php
=> [v3] update react http to 0.6

src/Sculpin/Core/Permalink/SourcePermalinkFactory.php, src/Sculpin/Core/Tests/Permalink/SourcePermalinkFactoryTest.php
Mutually exclusive to https://github.com/sculpin/sculpin/pull/234
Fixes issue #179, please see comment in Fixes issue #179, please see comment in https://github.com/sculpin/sculpin/issues/179#issuecomment-93811635
=> Fix issue #179 while keeping compability.

composer.json, composer.lock, src/Sculpin/Bundle/ThemeBundle/ThemeTwigExtension.php, src/Sculpin/Bundle/ThemeBundle/ThemeTwigLoader.php, src/Sculpin/Bundle/TwigBundle/FlexibleExtensionFilesystemLoader.php, src/Sculpin/Bundle/TwigBundle/TemplateResetter.php, src/Sculpin/Bundle/TwigBundle/TwigFormatter.php
PR for #337 
Incomplete migration, fixing only twig errors encountered by unit tests.
=> [v3] Update to twig v2

src/Sculpin/Bundle/ContentTypesBundle/Command/ContentCreateCommand.php, src/Sculpin/Bundle/PaginationBundle/PaginationGenerator.php, src/Sculpin/Bundle/SculpinBundle/HttpKernel/KernelFactory.php, src/Sculpin/Contrib/ProxySourceCollection/ProxySourceItem.php, src/Sculpin/Core/Console/Command/ContainerAwareCommand.php
There were several issues with the code sniffs, so I've addressed them here as best I can. In some cases I've bypassed doing a "full investigation" of what the cause is and just gone with fixes that satisfy phpcs and phpstan.
This could result in bad behaviour. The tests pass, though, so that's a positive sign.
=> Fix phpcs/phpstan checks

src/Sculpin/Bundle/ContentTypesBundle/DependencyInjection/SculpinContentTypesExtension.php, src/Sculpin/Bundle/ContentTypesBundle/Resources/config/services.xml, src/Sculpin/Bundle/SculpinBundle/Resources/config/services.xml, src/Sculpin/Bundle/StandaloneBundle/Resources/config/services.xml, src/Sculpin/Bundle/ThemeBundle/Resources/config/services.xml
Fix "PHP Deprecated: Auto-registration of the command"
See https://github.com/sculpin/sculpin/pull/381#issuecomment-397857036
PS I'm really very sorry that I have not been able to make PR for such a rapid change for a long time :(
ping @beryllium
=> Register commands as services

README.md
=> Remove obsolete HHVM badge

src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/GenerateCommandTest.php, src/Sculpin/Tests/Functional/GenerateFromMarkdownTest.php, src/Sculpin/Tests/Functional/GenerateFromPostsTest.php
=> Add PHP 7+ features for tests

bin/sculpin, bin/sculpin-phar-stub, bin/sculpin.php
=> Improvements of files in bin directory

composer.json
See https://github.com/sculpin/sculpin/blob/master/bin/sculpin.php#L50
cc @beryllium @simensen
=> Add ext-posix to composer.json

src/Sculpin/Bundle/ThemeBundle/ThemeTwigExtension.php
This is my mistake, sorry about that :(
@beryllium can you take PR as soon as possible?
=> Fix typing error if theme resource not found

src/Sculpin/Bundle/SculpinBundle/Command/GenerateCommand.php
It seems in my case, old habits are dying hard, as it were :disappointed: 
I got caught last night with this too.
=> Type hint on Throwable instead of Exception

src/Sculpin/Bundle/TwigBundle/TwigFormatter.php
no point in keeping commented out code
=> remove commented out code

src/Sculpin/Bundle/ContentTypesBundle/Command/ContentCreateCommand.php
- Makes "-b"/"--boilerplate" the default
- Adds a "-d"/"--dry-run" parameter to suppress file creation
- Updates the wording to be more helpful and instructive
=> Change the content:create command to create boilerplate files by default

.travis.yml, composer.json, composer.lock, phpunit.xml.dist, src/Sculpin/Bundle/SculpinBundle/Console/Application.php, src/Sculpin/Bundle/TwigBundle/WebpackEncoreHelper.php, src/Sculpin/Contrib/ProxySourceCollection/ProxySourceCollection.php, src/Sculpin/Contrib/ProxySourceCollection/ProxySourceCollectionDataProvider.php, src/Sculpin/Core/Permalink/SourcePermalinkFactory.php, src/Sculpin/Core/Tests/Source/CompositeDataSourceTest.php, src/Sculpin/Core/Tests/Source/Map/CalculatedDateFromFilenameMapTest.php, src/Sculpin/Tests/Functional/FunctionalTestCase.php, src/Sculpin/Tests/Functional/GenerateCommandTest.php, src/Sculpin/Tests/Functional/GenerateFromMarkdownTest.php
PHP 8 is out now. Sculpin has some small issues that this PR seeks to resolve.
=> Fixes for PHP 8

.github/workflows/phpstan.yml, composer.json, composer.lock, phpstan.neon, src/Sculpin/Bundle/ContentTypesBundle/Command/ContentCreateCommand.php, src/Sculpin/Bundle/SculpinBundle/Command/ContainerDebugCommand.php, src/Sculpin/Bundle/SculpinBundle/Command/GenerateCommand.php, src/Sculpin/Bundle/SculpinBundle/Command/ServeCommand.php, src/Sculpin/Bundle/SculpinBundle/HttpKernel/KernelFactory.php, src/Sculpin/Bundle/StandaloneBundle/Command/CacheClearCommand.php, src/Sculpin/Bundle/ThemeBundle/Command/ListCommand.php
Looks like the phpstan workflow may have been missing the composer installation step.
=> Add composer dependency checkout to the phpstan workflow

composer.json, composer.lock
https://github.com/textile/php-textile/security/advisories/GHSA-95m2-chm4-mq7m
=> Update netcarver/textile to fix security issue
